---
# tasks file for httpd
- name: Checking an installation and running
  shell: |
    httpd -version
    systemctl is-active httpd
  register: httpd_status
- debug: msg="{{ httpd_status.stdout_lines}}"
