---
# tasks file for jenkins
- name: Ensuring a file exists
  file:
    path: "{{ jenkins_path }}"
    state: directory    
- name: Downloading a jenkins war file
  get_url: 
    url: "{{ jenkins_war_url }}{{ jenkins_version }}/jenkins.war"
    dest: "{{ jenkins_war_path }}"
- name: Setting user-defined configuration options
  template: 
    src: jenkins.j2
    dest: /etc/sysconfig/jenkins
  notify: Restart Jenkins
- name: Creating jenkins service
  become: yes
  template:
    src: jenkins.service.j2
    dest: /etc/systemd/system/jenkins.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd
- name: Enabling and starting jenkins service
  become: yes
  systemd:
    name: jenkins.service
    enabled: yes
    state: started
- name: Checking an installation and running
  shell: |
    ls "{{ jenkins_war_path }}"
    systemctl is-active jenkins
  register: jenkins_status
- debug: msg="{{ jenkins_status.stdout_lines}}"
- name: Sleeping for 30 seconds and continue with play
  wait_for: timeout=30
  delegate_to: localhost
- name: Init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result
- name: Printing init password jenkins
  debug:
    var: result.stdout
