---
# defaults file for jenkins
jenkins_version: "2.136"
jenkins_war_url: "http://mirrors.jenkins.io/war/"
jenkins_name: "jenkins"
jenkins_java_opts:
   - "-Djava.awt.headless=true"
   - "-Djava.net.preferIPv4Stack=true"
jenkins_java_location: "/usr/bin/java"
jenkins_pidfile_path: "/var/run/jenkins/jenkins.pid"
jenkins_path: "/usr/share/jenkins"
jenkins_war_path: "/usr/share/jenkins/jenkins.war"
jenkins_home_path: "/var/lib/jenkins"
jenkins_run_standalone: "true"
jenkins_log: "/var/log/jenkins/jenkins.log"
jenkins_max_open_files: "8192"
jenkins_umask: "022"
jenkins_set_umask: False
jenkins_args:
  - "--webroot=/var/cache/jenkins/war"
  - "--httpPort=$HTTP_PORT"
jenkins_http_port: "8080"
user: "jenkins"
user_id: 1010
group: "jenkins"
group_id: 1010
