- name: Installing and configuring httpd
  hosts: 
    - webservers
  roles:
    - role: httpd
      become: yes
      become_user: root

- name: Installing and configuring jenkins
  hosts:
    - appservers
  roles:
    - role: devops_user
      tasks_from:
        - group
        - user
      become: yes
    - role: jenkins
      become: yes
