- name: Installing and configuring httpd
  hosts: 
    - webservers
  roles:
    - role: httpd
      become: yes
      become_user: root

- name: Installing and configuring jenkins
  hosts:
    - appservers
  roles:
    - role: java
      become: yes
      become_user: root
  tasks:
    - name: Downloading jenkins.repo
      get_url:
        url: "{{ jenkins_repo }}"
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Importing jenkins key
      rpm_key:
        state: present
        key: "{{ jenkins_repo_key }}"
    - name: Installing jenkins
      yum:
        name: jenkins
        state: present
    - name: Starting jenkins
      systemd:
        name: jenkins
        state: started
        enabled: yes
    - name: Sleeping for 30 seconds and continue with play
      wait_for: timeout=30
      delegate_to: localhost
    - name: Init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result
    - name: Printing init password jenkins
      debug:
        var: result.stdout
